version: '3.5'
services:
  app:
    build: .
    container_name: my-nestjs-app
    ports:
      - '3005:3000'
    environment:
      NODE_ENV: production
      PROMETHEUS_PORT: 9100
    env_file:
      - .env.docker
    depends_on:
      - prometheus
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    container_name: postgresCommandes
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9095:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3001:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana-data:
